
services:

  tiger-ledger-server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: tiger-ledger-server
    ports:
      - "8443:8443"
    depends_on:
      tigerbeetle:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - TIGER_BEETLE_CLUSTER=0
      - TIGER_BEETLE_HOST=tigerbeetle
      - TIGER_BEETLE_PORT=3000
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped
    networks:
      - tiger-network

  tigerbeetle:
    build:
      context: ./docker/tigerbeetle
    container_name: tigerbeetle
    ports:
      - "3000:3000"
    volumes:
      - tigerbeetle-data:/data
    security_opt:
      - "seccomp=unconfined"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/tigerbeetle", "version" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 3s
    networks:
      - tiger-network

  postgres:
    image: postgres:15
    container_name: tiger-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tigerledger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tiger-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: "tiger-cluster"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - tiger-network

  spark-streaming-job:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile
    container_name: spark-streaming-job
    depends_on:
      - kafka
    networks:
      - tiger-network

volumes:
  tigerbeetle-data:
  pgdata:
  kafka-data:

networks:
  tiger-network: