spring:
  application:
    name: tiger-ledger-service

  datasource:
    url: jdbc:postgresql://postgres:5432/tigerledger
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


