name: Run E2E Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Run docker-compose and wait for health endpoint
        run: |
          docker compose up -d --build
          
          echo "Waiting for Server health endpoint to return 200..."
          
          ATTEMPTS=0
          MAX_ATTEMPTS=30
          
          until curl -k --fail -o /dev/null -s https://localhost:8443/api/v1/health; do
            echo ""
            echo "🔄 Attempt $ATTEMPTS: Server not ready, waiting 5 seconds..."
            docker compose ps
            echo "📜 Server logs:"
            docker compose logs --no-color tiger-ledger-server | tail -n 50
            echo ""
            sleep 5
            ATTEMPTS=$((ATTEMPTS+1))
          
            if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]; then
              echo "❌ Server did not become healthy in time. Dumping full logs:"
              docker compose logs --no-color
              exit 1
            fi
          done
          
          echo "✅ Health endpoint returned 200!"
          docker compose ps

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run E2E Tests
        run: ./gradlew e2eTest --no-daemon --stacktrace

      - name: Tear down
        if: always()
        run: docker compose down